### ISSUE TITLE
[QUESTION] - External monitor

### ISSUE THREAD

**Issue by Livb-VRC** [erdilS/Port-Windows-11-Xiaomi-Pad-5#100]
### Question

I have a usb hub where I connect monitor/mouse/keyboard/mic/camera. The output is usb c 

This works fine for my mac and phone, and on windows 11 mi pad 5 it detects keyboard/mouse but not the monitor.

Is it possible for the monitor to somehow be detected?

### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by mohankrishnarao** [comment]
actually Xiaomi pad 5 type c  port doesn't support video out 
it's not software problem it's hardware problem
so there wont be any fix that issue 
and Xiaomi pad 6 is upgraded to port that allows video out

**Comment by n00b69** [comment]
Only possible with DisplayLink certified adapters
