### ISSUE TITLE
[BUG] - Huaxing screen not working after enabling OTG

### ISSUE THREAD

**Issue by senayuki** [erdilS/Port-Windows-11-Xiaomi-Pad-5#105]
### Description

The left side (vertical) displaied some strange, and the right side is completely black. I have to reboot the device.

After I restored the registry entries and flash the Huaxing boot, it returned to normal.

I tried to only recover the registry, but the problem still exists. I'm not sure if this is because the Huaxing screen requires a special boot image. After all, there are two different boot images provided during the installation process.

### Reproduction steps

```bash
Follow the instructions in troubleshooting, flashed boot and editted the registry. OTG is available. 
If I lock the screen and turn it on again, the display of the screen will be abnormal.
```

### Agreement

- [X] I am using the latest Drivers.
- [X] I am running Windows 11 On The Tablet.
- [X] There is no issue already describing my problem.

**Comment by bone6000** [comment]
same problem to me. when switch off screen strange lines appears in half part of the screen and the only option to recover from that is press the power button 15 secs. huaxing screen also

**Comment by TUEJJ** [comment]
I have the same problem

**Comment by Misha803** [comment]
this is already solved, update to latest  drivers and UEFI

**Comment by Misha803** [comment]
@senayuki this is already solved, update to latest drivers and UEFI

**Comment by senayuki** [comment]
> @senayuki this is already solved, update to latest drivers and UEFI

You're right, I upgraded UEFI and driver, and now it's working. Thanks!
