### ISSUE TITLE
[QUESTION] - QUESTION ABOUT CAMERA

### ISSUE THREAD

**Issue by alghiffaryfa19** [erdilS/Port-Windows-11-Xiaomi-Pad-5#111]
### Question

hello, can the camera be fixed using the Xiaomi Book S camera driver?

### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by n00b69** [comment]
No

Camera might not work for a long time, if ever
