### ISSUE TITLE
[QUESTION] - Can Mi PAD 6 run windows 11

### ISSUE THREAD

**Issue by s2kaka** [erdilS/Port-Windows-11-Xiaomi-Pad-5#113]
### Question

I wonder if Mi Pad 6 can run win 11 like this project. Maybe it will be support in the future?

Thanks

### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by erdilS** [comment]
No.
