### ISSUE TITLE
[QUESTION] - Is it normal for the 3ghz core to be throttled?

### ISSUE THREAD

**Issue by BomberPlayz** [erdilS/Port-Windows-11-Xiaomi-Pad-5#119]
### Question

Is it normal for the 3 ghz core in the pad 5 to be throttled to 800mhz, no matter what I do? Task manager is also reporting at most like 30% usage on that core, no matter what.

### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by xXPOLYGONXx** [comment]
Your question was answered here: https://github.com/map220v/MiPad5-Drivers/issues/8 
Since it is working as intended now you can probably close this issue.

**Comment by BomberPlayz** [comment]
It indeed looks like it has been fixed.
