### ISSUE TITLE
Audio distortion [BUG] - <title>

### ISSUE THREAD

**Issue by Ppkaim41** [erdilS/Port-Windows-11-Xiaomi-Pad-5#122]
### Description

Sound distortion problem while using Bluetooth,using gom player, cyberlink powerdvd ultra,vlc, windows media player,same problem with all software..no codecs available to change as aac,ldac..no dolby atmos driver....please fix the issue.. Bluetooth works well with pc and mac,can run kbps upto 1000..

### Reproduction steps

```bash
Audio driver update required as dolby atmos,or similar
```

### Agreement

- [X] I am using the latest Drivers.
- [X] I am running Windows 11 On The Tablet.
- [X] There is no issue already describing my problem.

**Comment by n00b69** [comment]
Does this still happen on the latest drivers?

**Comment by Pratikji44** [comment]
> Does this still happen on the latest drivers?

No issues now ..but can't change codecs

**Comment by n00b69** [comment]
Closing because it's resolved, for codecs you can try contacting map220v or gus33000
