### ISSUE TITLE
[BUG] - Dead tablet

### ISSUE THREAD

**Issue by itayalush** [erdilS/Port-Windows-11-Xiaomi-Pad-5#123]
### Description

Fastboot not working, I accidentally destroyed Android, Battery doesn't even charge and just drains, I can't get it working.

### Reproduction steps

```bash
It doesn't boot to fastboot, the battery drains in less than a minute.
```

### Agreement

- [X] I am using the latest Drivers.
- [X] I am running Windows 11 On The Tablet.
- [X] There is no issue already describing my problem.

**Comment by itayalush** [comment]
@erdilS pls help

**Comment by Xyy155** [comment]
uefi its use battery too much

**Comment by erictoman** [comment]
I can help

**Comment by Misha803** [comment]
@itayalush go to service centre or ask person ho have auth account, you need flash it in edl

**Comment by itayalush** [comment]
@Misha803 I got an EDL cable but it doesn't do anything.
@erictoman How can I DM on GitHub? you can email me in itay.alush.02@gmail.com

If anyone was wondering, I do have TWRP but it's black screen with only a little line at the top where display works. and it doesn't connect with ADB or MTP

**Comment by n00b69** [comment]
> @Misha803 I got an EDL cable but it doesn't do anything.

You can use https://mrauthtool.com/ to EDL flash your nabu (or other Xiaomi device). It will cost around 3-5 dollars.

Credits which are needed to use the flashing tool can be purchased with USDT through the Telegram vendors which are listed on the homepage.

You can use Telegram's @wallet to purchase USDT easily, they do however have higher fees than regular exchanges.

**Comment by erictoman** [comment]
> @Misha803 I got an EDL cable but it doesn't do anything.
> 
> @erictoman How can I DM on GitHub? you can email me `itay.alush.02@gmail.com` I'm only 11 but I do know a lot of things like how to install custom ROMs, Install Linux, and I even know Hackintosh (Porting macOS on normal PC) That's why I can't pay for an EDL authorized account. And also, how do I use an EDL authorized account? I can't enter Android, Can't enter Fastboot, TWRP has black screen and does not connect to ADB or MTP.

Are you still interested?

**Comment by Fizzi1470** [comment]
> > [@Misha803](https://github.com/Misha803) I got an EDL cable but it doesn't do anything.
> > [@erictoman](https://github.com/erictoman) How can I DM on GitHub? you can email me `itay.alush.02@gmail.com` I'm only 11 but I do know a lot of things like how to install custom ROMs, Install Linux, and I even know Hackintosh (Porting macOS on normal PC) That's why I can't pay for an EDL authorized account. And also, how do I use an EDL authorized account? I can't enter Android, Can't enter Fastboot, TWRP has black screen and does not connect to ADB or MTP.
> 
> Are you still interested?

I am if your offer is still available
