### ISSUE TITLE
Stuck on windows auto repair blue screen

### ISSUE THREAD

**Issue by Code691** [erdilS/Port-Windows-11-Xiaomi-Pad-5#124]
### Description

Need Help >> Everything worked great until my windows restarted for auto-repair, the windows auto repair blue screen came up AND i couldnt connect to any input method and the touch screen is not responsive to click on shut down. and when i tried to hard shut it down through the physical power button it restarted with the message that windows did not start properly, and again is asking me through the blue screen to click on restart, again i am unable to click that and i am stuck in the blue screen.

### Reproduction steps

```bash
Need to restart windows to reload properly through windows OS restart, Any code or method suggested?
```

### Agreement

- [X] I am using the latest Drivers.
- [X] I am running Windows 11 On The Tablet.
- [X] There is no issue already describing my problem.

**Comment by enggariel** [comment]
i also experiencing the same problem. how to solve it ?

**Comment by warriorkidz** [comment]
try this https://github.com/erdilS/Port-Windows-11-Xiaomi-Pad-5/issues/125#issuecomment-1879041337

**Comment by n00b69** [comment]
Reinstall windows
