### ISSUE TITLE
官方键盘可用 win 1121h版本 息屏问题已经解决   

### ISSUE THREAD

**Issue by luoqianlong1** [erdilS/Port-Windows-11-Xiaomi-Pad-5#129]
### Question

请更新

### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by Soneoylys** [comment]
Cannot confirm Keyboard working on latest Windows version.

在最新版Windows中键盘不工作.

**Comment by Misha803** [comment]
Keyboard now works! you can close this issue
