### ISSUE TITLE
[QUESTION] - Setting Windows size larger on Mi Pad 5

### ISSUE THREAD

**Issue by musapnr** [erdilS/Port-Windows-11-Xiaomi-Pad-5#130]
### Question

I did not start the installation. 

I have a 256GB tablet. I haven't started the installation yet. Would changing these commands to this work?

mkpart esp fat32 10.9GB 11.4GB
mkpart win ntfs 11.4 GB 209.8 GB
mkpart user data ext4 209.8 GB 254 GB

### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by Soneoylys** [comment]
Yes it will work, just make sure you do [sector alignment](https://en.wikipedia.org/wiki/4_KB_sector_alignment) correct, and the userdata space is enough for Android to at least initialize itself after partition.

**Comment by Misha803** [comment]
Bri it's OLD GUIDE, use new easy guide, with 2 command for partition

**Comment by n00b69** [comment]
Closed as it is the old guide. Use "adb shell partitiom 198.4" instead.
