### ISSUE TITLE
I HAVE A BIG PROBLEM [BUG] - <title>

### ISSUE THREAD

**Issue by Xyy155** [erdilS/Port-Windows-11-Xiaomi-Pad-5#136]
### Description

I HAVE A BIG PROBLEM

### Reproduction steps

```bash
if i switch to windows 
its show me 
press esc in 5 seconds to skip startup.nsh any other key to continue
and i try all UEFI NABU versons
but its not working
PLEASE help me
```

### Agreement

- [X] I am using the latest Drivers.
- [ ] I am running Windows 11 On The Tablet.
- [x] There is no issue already describing my problem.

**Comment by Misha803** [comment]
sound like you install wrong windows image, like X64 instead ARM64 or doesn't create bootloader files, please contact me in Telegram and i help you install it - https://t.me/misha803

**Comment by Misha803** [comment]
@Xyy155 sound like you install wrong windows image, like X64 instead ARM64 or doesn't create bootloader files, please contact me in Telegram and i help you install it - https://t.me/Misha803
