### ISSUE TITLE
It work on a mi pad 5 pro

### ISSUE THREAD

**Issue by oscarnu88** [erdilS/Port-Windows-11-Xiaomi-Pad-5#144]
### Question

Actually it work into a mi pad 5 pro? and how can I get the recovery.iso file

### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by Misha803** [comment]
No, it's only works on NABU (pad 5)

**Comment by Misha803** [comment]
@oscarnu88 No, it's only works on NABU (pad 5)

**Comment by Misha803** [comment]
@oscarnu88 are you here? if you haven't any questions now, you can close this issue
