### ISSUE TITLE
USB Drivers issue

### ISSUE THREAD

**Issue by hyunno0** [erdilS/Port-Windows-11-Xiaomi-Pad-5#149]
### Description

If Removing the components\QC8150\Device\DEVICE.SOC_QC8150.NABU\Drivers\USB folder, Drivers not installl...

### Reproduction steps

```bash
If Removing the components\QC8150\Device\DEVICE.SOC_QC8150.NABU\Drivers\USB folder, Drivers not installl...
```

### Logs

```bash
If Removing the components\QC8150\Device\DEVICE.SOC_QC8150.NABU\Drivers\USB folder, Drivers not installl...
```

### Agreement

- [X] I am using the latest Drivers.
- [X] I am running Windows 11 On The Tablet.
- [X] There is no issue already describing my problem.

**Comment by Misha803** [comment]
@hyunno0 we update deivers yesterday, try eeinstall it againg (with removed USB folder)

**Comment by n00b69** [comment]
Reopen an issue if this still happens on the latest drivers release
