### ISSUE TITLE
Charging problem...

### ISSUE THREAD

**Issue by hyunno0** [erdilS/Port-Windows-11-Xiaomi-Pad-5#155]
### Description

It has a big problem with Windows mode that doesn't charge...

### Reproduction steps

```bash
It has a big problem with Windows mode that doesn't charge...
```

### Agreement

- [X] I am using the latest Drivers.
- [X] I am running Windows 11 On The Tablet.
- [X] There is no issue already describing my problem.

**Comment by Misha803** [comment]
Charging in Windows only works on specific cables/chargers. One of the requirements appears to be an extra chip in the cable, such as the one on (official) Xiaomi (fast charging) cables.

Even with a working cable and charger, charging is usually rather slow.

IF YOU USE A POWERED USB HUB, DISABLE USB HOST MODE (enabled by default) OR YOU CAN DAMAGE YOUR NABU

**Comment by Misha803** [comment]
@hyunno0 
Charging in Windows only works on specific cables/chargers. One of the requirements appears to be an extra chip in the cable, such as the one on (official) Xiaomi (fast charging) cables.

Even with a working cable and charger, charging is usually rather slow.

IF YOU USE A POWERED USB HUB, DISABLE USB HOST MODE (enabled by default) OR YOU CAN DAMAGE YOUR NABU

**Comment by hyunno0** [comment]
When We use a powered USB Hub in Android Mode, not Windows Mode,  We must disable USB HOST MODE or  Our device can be damaged ?

**Comment by hyunno0** [comment]
How can we  disable USB HOST MODE ?...

**Comment by hyunno0** [comment]
C-types USB Hub don't matter, but USB Hub using A-type to C-type USB Gender are dangerous...
Also, there is no A-type USB Hub that supports charging...

**Comment by Misha803** [comment]
> e

no only in WIndows

**Comment by Misha803** [comment]
@hyunno0 just don't use powered USB hub

**Comment by n00b69** [comment]
> How can we disable USB HOST MODE ?...

https://github.com/erdilS/Port-Windows-11-Xiaomi-Pad-5/blob/main/guide/English/troubleshooting-en.md#charging-in-windows-does-not-work

**Comment by hyunno0** [comment]
When trying to charge with many types of cables, some cables show charging mode but not charging (current not flowing). This seems to be a problem with Windows drivers...
What is the solution?...

**Comment by hyunno0** [comment]
![20240304_212124 1](https://github.com/erdilS/Port-Windows-11-Xiaomi-Pad-5/assets/140943156/af6bbe67-d060-4fbb-90c3-bb9f1d70e906)

1 unknown device is the same as the image...
Which driver should I install?...

**Comment by n00b69** [comment]
> When trying to charge with many types of cables, some cables show charging mode but not charging (current not flowing). This seems to be a problem with Windows drivers... What is the solution?...

Charging is super slow. 10% battery in maybe 45 minutes
