### ISSUE TITLE
[QUESTION & SUGGESTION] - How can I build this project on my own?

### ISSUE THREAD

**Issue by EralpCelebi** [erdilS/Port-Windows-11-Xiaomi-Pad-5#156]
### Question

I have been trying to find a way to build this project from source but I have not been able to figure out how to do so. Where can I access the source for this project? It might be on me that I am missing something in the documentation but I (and many others probably) would appreciate it if it was clearer to a newcomer. 

Also: I don't know if including a guide on how to activate Windows and Office is a good idea for a public project like this. I would suggest removing them from the documents.

### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by n00b69** [comment]
What exactly are you trying to build?

**Comment by EralpCelebi** [comment]
The UEFI image.

**Comment by n00b69** [comment]
> The UEFI image.

https://github.com/map220v/MU-sm8150pkg/commits/nabu-secureboot

**Comment by Misha803** [comment]
> > The UEFI image.
> 
> https://github.com/map220v/MU-sm8150pkg/commits/nabu-secureboot

it's old i think, this repo isn't updated

**Comment by EralpCelebi** [comment]
Thank you @n00b69
