### ISSUE TITLE
[BUG] - install.esd installation error

### ISSUE THREAD

**Issue by galaxysollector** [erdilS/Port-Windows-11-Xiaomi-Pad-5#157]
### Install

> Replace `<path/to/install.esd>` with the actual path of install.esd

> If you got your Windows image elsewhere (which might also be called `install.wim`), replace `index:6` with `index:1`
```cmd
dism /apply-image /ImageFile:<path/to/install.esd> /index:6 /ApplyDir:X:\
```

In this situation, my ko-kr install.esd has no index 6 so I got error 87. I changed index to 5 and now it works. I think that en-us install.esd has index 6 but ko-kr does not.

### Reproduction steps

Use ko-kr install.esd and enter this, "dism /apply-image /ImageFile:<path/to/install.esd> /index:6 /ApplyDir:X:\". Then cmd prints error 87. I am sure that index number is different depend on language.

### Agreement

- [X] I am using the latest Drivers and UEFI.
- [X] I am running Windows 11 on the tablet.
- [X] There is no issue already describing my problem.

**Comment by Misha803** [comment]
@galaxysollector yes, right, en-us install.esd has index 6 but ko-kr does not. We will add it as note soon
