### ISSUE TITLE
[BUG] - Flash light does not work.

### ISSUE THREAD

**Issue by galaxysollector** [erdilS/Port-Windows-11-Xiaomi-Pad-5#160]
## How to use Flashlight 

 - Download [Flashlight.7z](https://github.com/erdilS/Port-Windows-11-Xiaomi-Pad-5/releases/download/1.0/flashlight_fix.7z) and unzip to any folder

> Press any key to disable it

In this situation, I ran flashlight.exe but it does not work.

> ![스크린샷 2024-02-28 235921](https://github.com/erdilS/Port-Windows-11-Xiaomi-Pad-5/assets/99175924/3df02b6f-99c1-4f4d-94be-1a119c8a99a5) to enable flashlight 

### Reproduction steps

```bash
Run flashlight.exe
```

### Agreement

- [X] I am using the latest Drivers and UEFI.
- [X] I am running Windows 11 on the tablet.
- [x] There is no issue already describing my problem.

**Comment by Misha803** [comment]
@galaxysollector can you show me screenshot of device manager? it there any devices with errors? you also can try any flash light app from Microsoft store

**Comment by galaxysollector** [comment]
> @galaxysollector can you show me screenshot of device manager? it there any devices with errors? you also can try any flash light app from Microsoft store

There is no error in device manager but the result is same.

**Comment by Misha803** [comment]
> > @galaxysollector can you show me screenshot of device manager? it there any devices with errors? you also can try any flash light app from Microsoft store
> 
> There is no error in device manager but the result is same.

Did you tried  any flashlight app?

**Comment by galaxysollector** [comment]
> > > @galaxysollector can you show me screenshot of device manager? it there any devices with errors? you also can try any flash light app from Microsoft store
> > 
> > 
> > There is no error in device manager but the result is same.
> 
> Did you tried any flashlight app?

Yes but it looks like not working. I updated driver today but the result is still same.

**Comment by Misha803** [comment]
hm, strange, if you sure that in device manager you haven't any devices with errors i will report it to dev

**Comment by Misha803** [comment]
cab you check cameras page and send me screenshot ?

**Comment by Misha803** [comment]
dev say that flashlight was broken in latest drivers, just wait for fix

**Comment by Misha803** [comment]
Btw it should work with latest drivers via Windows Camera app
