### ISSUE TITLE
can't connect to wifi

### ISSUE THREAD

**Issue by Edward-Lucas** [erdilS/Port-Windows-11-Xiaomi-Pad-5#17]
I followed the guide and installed normally, but there are two big problems.Wifi doesn't work. If you turn off the screen, the device powers off, and if you connect the charger in this state, it enters fastboot mode.

**Comment by warpreality** [comment]
wifi fixed after reboot

**Comment by halal-beef** [comment]
second issue already known and most likely cant be fixed without qcom gpu source

**Comment by IliyaBrook** [comment]
In my case rebooting not make effect =((, i also tried to use bypass and update the driver manually after removed the driver from system management....also no wifi...

**Comment by priteshz** [comment]
> [IliyaBrook](/IliyaBrook)

I had similar issue, wifi conn detected and connected at time of setup but if i click next, it shows that it disconnected
I went around the issue by clicking retry<>Next button rapidly
