### ISSUE TITLE
[BUG] - Keyboard not worked on repair mode 

### ISSUE THREAD

**Issue by KernelSU123** [erdilS/Port-Windows-11-Xiaomi-Pad-5#173]
### Description

I'm facing a problem, I need to update a driver, but to do that I need to disable the digital signature of the drivers, to do that I need to reboot the OS while holding down shift, and get into recovery mode, but I can't select "advanced boot options" as my keyboard is disabled in repair mode, fix it in uefi no secureboot and reply me. Thanks

### Reproduction steps

```bash
Enable keyboard in uefi(bios)
```

### Agreement

- [X] I am using the latest Drivers and UEFI.
- [X] I am running Windows 11 on the tablet.
- [X] There is no issue already describing my problem.

**Comment by n00b69** [comment]
Not really possible to fix, and what driver are you trying to update? Drivers can be updated with OnlineUpdater in the driver zip.

**Comment by KernelSU123** [comment]
>  what driver are you trying to update?

I'm trying to update the adb drivers
