### ISSUE TITLE
Can i install windows on mi pad 6?

### ISSUE THREAD

**Issue by 4irjej** [erdilS/Port-Windows-11-Xiaomi-Pad-5#182]
### Question

![s-l1200](https://github.com/erdilS/Port-Windows-11-Xiaomi-Pad-5/assets/88525483/e6201af6-2ed7-4b03-acdb-05ce13f0381b)

Since mi pad 5 discontinued its possible to install windows 11?

### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by Misha803** [comment]
no, this is a guide for installing Windows on NABU only

**Comment by Misha803** [comment]
you can install Windows on pad  6 but there is no touch, wi-fi, sound

**Comment by Misha803** [comment]
better wait for Xiaomi pad 6S pro, or buy pad 5

**Comment by n00b69** [comment]
No
