### ISSUE TITLE
[QUESTION] - Resizing partitions

### ISSUE THREAD

**Issue by alfsoft** [erdilS/Port-Windows-11-Xiaomi-Pad-5#186]
### Question

Hi! Can we somehow resize partitions without reinstalling everything? I initially set my Android partition to be only 16 Gb, but now I want to increase it by shrinking Windows partition. Can we do it without loosing our Windows or Android user data?

### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by n00b69** [comment]
You can resize Windows but you will lose Android data, or vice versa. But neither is recommended.
