### ISSUE TITLE
Low audio quality

### ISSUE THREAD

**Issue by AdrMC2** [erdilS/Port-Windows-11-Xiaomi-Pad-5#187]
### Description

Hello, the sound quality is quite terrible. It is heard with low quality, and since these are the only drivers there are for this tablet with Windows, I wanted to ask if anyone else has the same problem and if there would be any option to improve the audio quality. Otherwise, the Windows tablet is perfect

### Reproduction steps

```bash
Low quality
```

### Agreement

- [X] I am using the latest Drivers and UEFI.
- [X] I am running Windows 11 on the tablet.
- [X] There is no issue already describing my problem.

**Comment by Jbrimbelibap** [comment]
Could be an issue specific to your tablet, speakers sound good on mine

**Comment by n00b69** [comment]
Asking about it in the Telegram, it seemslike most people have this issue. The audio in Windows is nit as good as in Android.

**Comment by AdrMC2** [comment]
Hello, I was doing sound tests on the tablet in Android mode and Windows mode and there is a big difference in the sound. In Android mode you can hear it with very good quality, the sound is very clear, and in Windows mode it completely loses the quality that it has in Android, I looked at the drivers to see if they were updated and everything was fine, but it still sounds bad

**Comment by n00b69** [comment]
Likely unfixable, the same issue also affects other Android-WoA devices
