### ISSUE TITLE
[QUESTION] - <title>Battery capacity always returns to 100% when plugged in.

### ISSUE THREAD

**Issue by vtungabc** [erdilS/Port-Windows-11-Xiaomi-Pad-5#190]
### Question

Battery capacity always returns to 100% when plugged in. And the battery is not charged either. It will gradually reduce the battery level as it does in Android. The dangerous problem is that the battery percentage is wrong. How to fix ?

### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by n00b69** [comment]
Charging in Windows only works on specific cables/chargers. One of the requirements appears to be an extra chip in the cable, such as the one on (official) Xiaomi (fast charging) cables.

Even with a working cable and charger, charging is usually rather slow. DEAD slow. Expect speeds of 10% per hour, if not less.

This unfortunately cannot be fixed, at least not anytime soon
