### ISSUE TITLE
[QUESTION] - cant run usb host mode control app

### ISSUE THREAD

**Issue by plants8332** [erdilS/Port-Windows-11-Xiaomi-Pad-5#191]
### Question

Im currently using Windows 11 Pro, but for some reason every time I open "USB.Host.Mode.Control.V7.0.exe" it gives me this error. Im running it as a administrator but still the same error. How can i fix this?
![image](https://github.com/erdilS/Port-Windows-11-Xiaomi-Pad-5/assets/78642947/32bdbef3-3bdf-41de-8b8e-6690df651284)

### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by bibarub** [comment]
you're supposed to run it on your tablet

**Comment by plants8332** [comment]
my bad g 😭
