### ISSUE TITLE
The WINNABU partition can't be found. Please ensure that you have run MSC and haven't missed the device partitioning step

### ISSUE THREAD

**Issue by blimer** [erdilS/Port-Windows-11-Xiaomi-Pad-5#194]
### Description

I have unlocked bootloader and rooted device (xiaomi pad 5 6/64).
I previously installed Windows using an old guide, and it worked without any issues.
Now i am stuck in step "Assign letters to WINNABU and ESPNABU partitions"
![image](https://github.com/erdilS/Port-Windows-11-Xiaomi-Pad-5/assets/7001640/6ccb671c-9ead-4024-8972-b9aace124e9a)
![image](https://github.com/erdilS/Port-Windows-11-Xiaomi-Pad-5/assets/7001640/11720a85-9821-4b78-b143-b769ff36ba78)
![image](https://github.com/erdilS/Port-Windows-11-Xiaomi-Pad-5/assets/7001640/9e27d8bc-64a4-4667-899d-eac3a041c614)

### Reproduction steps

```bash
Fresh install rom V14.0.8.0.TKXEUXM
Root the rom via magisk
Get Stuck in step: Assign letters to WINNABU and ESPNABU partitions
```

### Logs

```bash
Press Y to continue, or N to cancel.
Do you want to proceed? (Y/N): Y
The WINNABU partition can't be found. Please ensure that you have run MSC and haven't missed the device partitioning step

press any key to exit
```

### Agreement

- [X] I am using the latest Drivers and UEFI.
- [X] I am running Windows 11 on the tablet.
- [X] There is no issue already describing my problem.

**Comment by Misha803** [comment]
looks like you doesn't partitioned the device

**Comment by Misha803** [comment]
oh wait, you reinstalling Windows, right?

**Comment by Misha803** [comment]
btw can you contact me on Telegram - https://t.me/misha_803. It will be better to speak there

**Comment by Misha803** [comment]
oh wait, you reinstalling Windows maybe ?
