### ISSUE TITLE
[QUESTION] - Is it possible to use WSL or Docker Desktop?

### ISSUE THREAD

**Issue by marc-hg** [erdilS/Port-Windows-11-Xiaomi-Pad-5#201]
### Question

Is it possible to use WSL or Docker Desktop?

### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by n00b69** [comment]
Only WSL1, WSL2 and Docker both require virtualization which is not supported and will never be supported.

**Comment by zxcwsurx** [comment]
@n00b69 send your legs day 1
