### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by blimer** [erdilS/Port-Windows-11-Xiaomi-Pad-5#21]
Hey, I install new driver from your link. The icon show that the system have sound card but the sound not working. Always is silent
![Zrzut ekranu 2023-01-30 102835](https://user-images.githubusercontent.com/7001640/215439788-fce29fa1-2bdc-48e9-a169-42166dde7a7c.png)
![Zrzut ekranu 2023-01-30 103220](https://user-images.githubusercontent.com/7001640/215439802-5a623c29-2972-4c04-9e1b-9fe1aec0d1c2.png)

**Comment by kmille36** [comment]
Flash new UEFI image.
