### ISSUE TITLE
[QUESTION] - Install on xiaomi pad 5 cn 8gb ram

### ISSUE THREAD

**Issue by 2020loryx** [erdilS/Port-Windows-11-Xiaomi-Pad-5#231]
### Question

It is possible to install windows on a xiaomi pad 5 china version with 8gb ram? (It isn't a xiaomi pad 5 pro)

### Agreement

- [x] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by n00b69** [comment]
Yes it is possible, the only difference is RAM.

The only exception is if you are using a Chinese version with modded UFS (512GB/1TB), these are currently not supported by the partitioning script (because we don't have some values needed to make it work).

**Comment by 2020loryx** [comment]
Ok thak you, so i don't need other drivers and windows will recognize the whole 8gb right?

**Comment by n00b69** [comment]
Correct

**Comment by 2020loryx** [comment]
Thank you for the help

**Comment by Gezine** [comment]
Sorry to revive this issue but where can I get information about 8GB mi pad5?
Never heard of it.

**Comment by n00b69** [comment]
It is only available in China

**Comment by Gezine** [comment]
So we can use same uefi file for 8GB version?
