### ISSUE TITLE
[BUG] - <title> Sleep Mode

### ISSUE THREAD

**Issue by ericf2k24** [erdilS/Port-Windows-11-Xiaomi-Pad-5#247]
### Description

A reboot or a hard restart is needed when the Mi pad is put on sleep mode for more than 5 minutes. I tried tweaking power options: Change when the computer sleeps; Change advanced power settings; Hard disk: set both on battery and plugged to 10080 (7days?). I was able to use win 11 normally after 6 hours of sleep mode without reboot.

### Reproduction steps

```bash
Open Control Panel, Click Power Option, click Change when the computer sleeps, click Change advanced power settings, click plus sign on hard disk, click, click plus sign on turn of hard disk after. set both option to 10080 minutes or 7 days...i think.
```

### Agreement

- [X] I am using the latest Drivers and UEFI.
- [X] I am running Windows 11 on the tablet.
- [X] There is no issue already describing my problem.

**Comment by n00b69** [comment]
If it only happens with advanced power options, try reverting the changes you made
