### ISSUE TITLE
[BUG] - <auto-rotation unavailable>

### ISSUE THREAD

**Issue by KOTORIcc** [erdilS/Port-Windows-11-Xiaomi-Pad-5#249]
### Description

After updating the latest drivers , the screen auto-rotation feature seems to be unavailable
<img width="359" alt="屏幕截图 2024-10-01 001702" src="https://github.com/user-attachments/assets/ec5122fd-3f16-4d15-b7f3-9b244dfbe9b0">

### Reproduction steps

```bash
osversion: windows 11 23h2
```

### Agreement

- [X] I am using the latest Drivers and UEFI.
- [X] I am running Windows 11 on the tablet.
- [X] There is no issue already describing my problem.

**Comment by n00b69** [comment]
Show me the sensor device(s) in device manager

**Comment by timoxa0** [comment]
Also check if HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\PriorityControl\ConvertibleSlateMode is set to 1 in the registry, if so reset it to 0 to activate autorotation

**Comment by KOTORIcc** [comment]
it works，thanks.👌
