### ISSUE TITLE
[QUESTION] - <title>

### ISSUE THREAD

**Issue by SheriffHU** [erdilS/Port-Windows-11-Xiaomi-Pad-5#252]
### Question

Hello, I would like to ask if this whole method is technical on a xiaomi mi pad 6 device? Because I would really like to try it out and even need such a Windows system. 

### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by n00b69** [comment]
Possible but there are no drivers, therefore nothing works
