### ISSUE TITLE
[QUESTION] - <Battery level>

### ISSUE THREAD

**Issue by soldaire123** [erdilS/Port-Windows-11-Xiaomi-Pad-5#253]
### Question

Good evening everyone , i have problem with battery level in Windows 11 on Mi Pad 5 . is still give same level percent charge whole time but if restart system or boot to Android is give me the right percent charge level .

### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by n00b69** [comment]
Unfortunately not fixable. Sometimes it works, sometimes it does not. Usually it will show the correct percentage after it drops around 30%.
