### ISSUE TITLE
[QUESTION] - Access to Cellular or SMS texts from Windows?

### ISSUE THREAD

**Issue by Espionage724** [erdilS/Port-Windows-11-Xiaomi-Pad-5#277]
### Question

I'm wondering if there's a way to view SMS texts and/or do voice calls over cellular while running Windows? Last I tried with W10 on a OnePlus 6, LTE data worked. I have VoLTE and VoWiFi on Android (stock OOS and LineageOS 21).

### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by n00b69** [comment]
Nabu has no LTE support

**Comment by miask** [comment]
可以通过一个win11自带的工具满足你的需求，叫手机连接，他可以把任何来自手机的通知通过这个工具推送到你的windows上，并且允许你在windows上进行拨打电话和发送短信等，支持Android和ios，原理似乎是通过蓝牙，如果你想nabu独立完成这些，是不可行的
