### ISSUE TITLE
[QUESTION] - Partition Custom ROM Xiaomi Pad 5

### ISSUE THREAD

**Issue by smartfrenard** [erdilS/Port-Windows-11-Xiaomi-Pad-5#285]
### Question

I have custom ufs, upgrade from 256 Gb to 512 Gb for Xiomi Pad 5. How to partition for custom rom 512 Gb?
![Screenshot 01](https://github.com/user-attachments/assets/8745fa96-3342-484d-b211-0832f6137c9d)
![Screenshot 02](https://github.com/user-attachments/assets/12c125f6-6a6c-420e-8a11-eb2dd8aaf8a4)

### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by n00b69** [comment]
Please run the below command and send a picture

```cmd
adb shell blockdev --getsize64 /dev/block/sda
```

After that, use these steps to partition:

```cmd
adb shell sgdisk --resize-table=128 /dev/block/sda
```

```cmd
adb shell parted /dev/block/sda
```

```cmd
rm 31
```

Replace 256GB with whatever you want Android to have
```cmd
mkpart userdata ext4 10.9gb 256gb
```

Replace 256 with the value you used in userdata
```cmd
mkpart esp fat32 256gb 256.35gb
```

Same here with 256
```cmd
mkpart win ntfs 256.35gb 509gb
```

```cmd
set 32 esp on
```

```cmd
quit
```

```cmd
adb shell mkfs.ntfs -f /dev/block/sda33 -L WINNABU
```

```cmd
adb shell mkfs.fat -F32 -s1 /dev/block/sda32 -n ESPNABU
```

Format data in ofox and check if android boots, then reboot back to recovery and do the steps on the second page

**Comment by smartfrenard** [comment]
adb shell blockdev --getsize64 /dev/block/sda

![Screenshot 2024-11-24 072048](https://github.com/user-attachments/assets/7ba81939-3f20-433e-832e-45864efac869)

**Comment by smartfrenard** [comment]
Next Step page 3 guide/English/3-install-en.md, can't run execute msc?

![Screenshot 2024-11-24 085235](https://github.com/user-attachments/assets/9f737127-2fff-4251-84ea-b536b391f772)
![Screenshot 2024-11-24 085159](https://github.com/user-attachments/assets/aa1559d2-c514-452b-97c9-b873661eb9a0)

**Comment by n00b69** [comment]
Give me some time, I'll add 512GB support to the recovery

**Comment by n00b69** [comment]
Boot this recovery

https://github.com/erdilS/Port-Windows-11-Xiaomi-Pad-5/releases/download/1.0/512.img

Try `adb shell partition $`

Then try `adb shell msc`

**Comment by smartfrenard** [comment]
Sorry, I forgot to tell you my custom nabu 8/512Gb.
Successfully install driver using latest version but always restart and blue screen? is the driver incompatible for nabu custom 8/512Gb?

![Screenshot 2024-11-24 201345](https://github.com/user-attachments/assets/068e4e4d-5d24-4fc6-bb43-b0f56809951c)
![Screenshot 2024-11-24 201316](https://github.com/user-attachments/assets/1fb6d384-b0ae-448b-abbf-6a7f994e3916)
![Screenshot 2024-11-24 201443](https://github.com/user-attachments/assets/659d170c-59e0-4804-ad03-5f3a2dec77fd)
![Screenshot_20241124_195224_com huawei photos_edit_337519658282870_082455](https://github.com/user-attachments/assets/53978648-b767-4cd3-886f-a85bb89b7554)
![Screenshot_2024-11-24-20-25-44-329_com android settings](https://github.com/user-attachments/assets/b94b8c20-9315-4f84-b535-edcb86127c4f)
![Screenshot_2024-09-14-18-20-08-779_com mi android globalFileexplorer](https://github.com/user-attachments/assets/fbc49b4d-b816-41e9-ac81-b68c63d08176)
![Screenshot_2024-11-24-20-17-49-275_id kuato woahelper](https://github.com/user-attachments/assets/828bea48-5cc8-48c3-962c-1e1f22488e24)

https://github.com/user-attachments/assets/4c6ff93e-5dbb-430c-b9e5-a855d090dc3e

**Comment by n00b69** [comment]
Try `adb shell format` and try reinstall Windows, might be just a random bug.

**Comment by n00b69** [comment]
Closing, assuming it was fixed
