### ISSUE TITLE
Do printers work on windows 11

### ISSUE THREAD

**Issue by midnextlevel** [erdilS/Port-Windows-11-Xiaomi-Pad-5#288]
### Question

Im wondering if anyone tried printing via usb port

### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by n00b69** [comment]
They should work if ARM64 drivers are available

**Comment by midnextlevel** [comment]
i see thanks for the reply
