### ISSUE TITLE
[QUESTION] - "adb shell fixgpt" command not found ERROR

### ISSUE THREAD

**Issue by doctormord** [erdilS/Port-Windows-11-Xiaomi-Pad-5#297]
### Question

Hi,

i wanted to fix the GPT after updating the Windows to 24H2 as noted on:

https://github.com/erdilS/Port-Windows-11-Xiaomi-Pad-5/blob/main/guide/English/fix-gpt-en.md

Unfortunately, the command "adb shell fixgpt" does not work as it can't be found.

`c:\test\platform-tools>adb shell fixgpt
/sbin/sh: fixgpt: command not found`

How can i fix this?

Best regards

Christian

### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by n00b69** [comment]
Redownload the recovery.img, it should work now
