### ISSUE TITLE
[QUESTION] - c:\sta gone after updating from 23h2 to 24h2

### ISSUE THREAD

**Issue by doctormord** [erdilS/Port-Windows-11-Xiaomi-Pad-5#298]
### Question

Hi,

after updating the Windows installation from 23h2 to 24h2 via Windows Update, the c:\sta folder is gone so i can't boot into Android now.

Is there any way to fix this from within Windows?

Thanks and best regards

Christian

### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by n00b69** [comment]
Redownload sta.exe here https://t.me/nabuwoa/281208
