### ISSUE TITLE
[QUESTION] - Xiaomi Pad 6S Pro

### ISSUE THREAD

**Issue by JiriKiner** [erdilS/Port-Windows-11-Xiaomi-Pad-5#313]
### Question

Hello. Is there a way to make this work on a Xiaomi Pad 6S Pro? Thank you in advance.

### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by n00b69** [comment]
No

**Comment by remtrik** [comment]
@JiriKiner Yes

**Comment by JiriKiner** [comment]
So is it a yes or no? If yes, how? Thank you

**Comment by n00b69** [comment]
Technically yes but nothing works and it probably won't for a very long time either.
