### ISSUE TITLE
Xiaomi Pad 5 Pro 12.4

### ISSUE THREAD

**Issue by arvbs** [erdilS/Port-Windows-11-Xiaomi-Pad-5#39]
### Question

Can be installed on Xiaomi Mipad 5 Pro 12.4?

### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by arvbs** [comment]
Now there is a lightweight build of Windows 11 Tiny that runs on just 2 GB of RAM.
Maybe it is possible to port it somehow?

**Comment by erdilS** [comment]
No, sm8250 (865/865+/870) not supported by Renegade Project.
