### ISSUE TITLE
Stuck on BSOD automatic start up repair

### ISSUE THREAD

**Issue by hummy2805** [erdilS/Port-Windows-11-Xiaomi-Pad-5#45]
### Description

after several reboots. windows 11 on mi pad 5 loops at automatic startup repair BSOD
can't choose option in bluescreen such as advanced mode/trouble shooting mode. bcoz no mouse and keyboard function

### Reproduction steps

```bash
after several reboots. windows 11 on mi pad 5 loops at automatic startup repair BSOD
can't choose option in bluescreen such as advanced mode/trouble shooting mode. bcoz no mouse and keyboard function
```

### Logs

```bash
after several reboots. windows 11 on mi pad 5 loops at automatic startup repair BSOD
can't choose option in bluescreen such as advanced mode/trouble shooting mode. bcoz no mouse and keyboard function
```

### Agreement

- [X] I am using the latest Drivers.
- [X] I am running Windows 11 On The Tablet.
- [X] There is no issue already describing my problem.

**Comment by itayalush** [comment]
fuck this shit... i have this problem too

**Comment by shalabh46** [comment]
i had same problem. how to recover.

**Comment by Xyy155** [comment]
try it enter to fastboot and reroot your device with "fastboot flash boot (your root file location in pc)" and type
"fastboot reboot" now your device on android and reinstall windows

**Comment by bone6000** [comment]
anyway to recover without reinstalling windows again? I have some configurations and apps installed, i don't want to loose all my job

**Comment by n00b69** [comment]
Open a new issue if this still happens, in the meantime the guide and the install method has been updated extensively.
