### ISSUE TITLE
[QUESTION] - Good news ! Charging work!!! <title>

### ISSUE THREAD

**Issue by kmille36** [erdilS/Port-Windows-11-Xiaomi-Pad-5#48]
### Question

I can charge while I'm on Windows ( 12.2v 1.3A). XD

Flash this UEFI into boot in fast boot mode: https://github.com/kmille36/TempStorage/blob/main/xiaomi-nabu.img?raw=true

Update to latest Drivers: https://github.com/erdilS/Port-Windows-11-Xiaomi-Pad-5/blob/main/guide/driver-updating-selection.md

Modifying value in Regedit: Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Enum\ACPI\QCOM0597\0\Device Parameters (RoleSwitchMode 3 to 1). Then restart Windows!

*Tested with C to C charging (with PD support), Xiaomi 33W charge work (already tested)*

![image](https://user-images.githubusercontent.com/58414694/228883879-5c31a8e0-876e-42ae-b013-ba676b212d7e.png)
![image](https://user-images.githubusercontent.com/58414694/228883912-d7c6d281-5c9f-4b80-9088-7adb3d95b994.png)

You need to plug in the charger before Windows bootup, otherwise, it will not charge... (please keep the cable plugged in, if u unplug it will not charge until you shut down Windows and plug in charge before bootup).

Also USB type C Apdater work!!!

### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by priteshz** [comment]
I am getting charging but the charging percentages keep dropping while being plugged anyway, just like before i used your steps

**Comment by priteshz** [comment]
There appears to be a bug with charging percentages (MI Pad is 2 months old and battery is fine)
The percentage reaches 100 and then bounce back to 75, then start increasing again, and then repeats

**Comment by priteshz** [comment]
@kmille36 charging stop at 80%, is that intentional?

**Comment by krvrian** [comment]
hey i tried this yet it still not charging, any clue?

**Comment by kmille36** [comment]
> hey i tried this yet it still not charging, any clue?

Use type c to c charger

**Comment by krvrian** [comment]
> Use type c to c charger

oh I tried using macbook's charger and it's charging now, thank you

**Comment by Emilia-sama** [comment]
Using the uefi and the newest driver bring BSOD problem, error on code INTERNAL_POWER_ERROR
From my observation, it load windows with 6w charge rate and when it almost done loading it crashed. Same goes to everytime shutting off the pad5 even tho no charger was connected. Switching the registry file doesn't bring any changes.

On event viewer also didnt mentioned the driver that causes this, only notes that it says is the device lose power

**Comment by n00b69** [comment]
Charging is enabled by default now due to the USB host mode tweak
