### ISSUE TITLE
NO SUPPORT FOR OTG

### ISSUE THREAD

**Issue by HGNEO** [erdilS/Port-Windows-11-Xiaomi-Pad-5#63]
### Description

THE TAB DOES NOT READ ANY OTG LIKE PENDRIVE OR KEYBOARD AND MOUSE RESPECTES SIR/MAM,PLEASE ADD SUPPORT FOR THIRD PARTY OTGS BECAUSE WE ALL HERE ARE NOT RICH ENOUGH FOR. BUYING ANY OFFICIAL KEYBOARD SO PLEASE SIR/MAM

### Reproduction steps

```bash
JUST CONNECT THE OTG AND TRY CONNECTING ANY USB PEN DRIVE OR MOUSE OR KEYBOARD USING IT YOU WONT BE ABLE TO DO SO
```

### Agreement

- [X] I am using the latest Drivers.
- [X] I am running Windows 11 On The Tablet.
- [X] There is no issue already describing my problem.

**Comment by priteshz** [comment]
https://github.com/erdilS/Port-Windows-11-Xiaomi-Pad-5/blob/main/guide/English/troubleshooting-en.md#how-to-charging-and-usb-guide

OTG is supported. Use this guide to enable OTG, close the bug when and if it resolves the issue.
