### ISSUE TITLE
[QUESTION] Port-Windows-11-Xiaomi-Pad-6 and Support for Xiaomi-Pad-5-Pro-12.4

### ISSUE THREAD

**Issue by justGits** [erdilS/Port-Windows-11-Xiaomi-Pad-5#65]
### Question

The performance improvements on (SD870 SoC) is up 20% and it is about as fast as Surface Pro X (SQ1 SoC) that cost significantly more at a price of $999.

Now they are people asking for a lower price that cost $500 less can buy Xiaomi Pad 5 Pro 12.4(SD870 SoC) or Xiaomi Pad 6(SD870 SoC) if it can offer same Windows 11 support from the older model of Xiaomi Pad 5. 

### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by kmille36** [comment]
Hope they support it in the future.

**Comment by erdilS** [comment]
SM8250 (865/865+/870) will not supported by Renegade Project due missing source codes from Qualcomm.
