### ISSUE TITLE
Please someone help increasing windows storage without having to re install

### ISSUE THREAD

**Issue by ItsnacioCh** [erdilS/Port-Windows-11-Xiaomi-Pad-5#66]
### Question

Help, i want to increase the storage on windows and decrease the storage on android, without having to re install.

Is it possible? Need assistance

### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by priteshz** [comment]
I have removed the userdata partition from windows and merged it with WIN partition. I have later used uninstall script and it worked fine. So i can confirm that this method works without bricking the device.

**Comment by priteshz** [comment]
![IMG_20230429_123422.jpg](https://user-images.githubusercontent.com/73827280/235288881-b784423f-1c7a-4deb-9b6b-bb0babf98275.jpg)

![IMG_20230429_123408.jpg](https://user-images.githubusercontent.com/73827280/235288880-3f8bd8ad-4069-4257-a8c7-562359d53ca3.jpg)

**Comment by kmille36** [comment]
OK Great !

**Comment by Emilia-sama** [comment]
> I have removed the userdata partition from windows and merged it with WIN partition. I have later used uninstall script and it worked fine. So i can confirm that this method works without bricking the device.

can you boot back to android? doesn't uninstall script restore original storage to android? leaving no space for windows at all

**Comment by priteshz** [comment]
> > I have removed the userdata partition from windows and merged it with WIN partition. I have later used uninstall script and it worked fine. So i can confirm that this method works without bricking the device.
> 
> can you boot back to android? doesn't uninstall script restore original storage to android? leaving no space for windows at all

Yes, what i meant is that we can safely merge userdata partition from windows and increase windows storage

By mentioning uninstall script i meant that the change is reversible without bricking the device

Warning ⚠️: do not touch any other partition, just carefully delete userdata carefully and expand WINNABU partition with that space.

**Comment by musapnr** [comment]
> Lol u can not without losing data both. Need to format partition.

mkpart esp fat32 10.9GB 11.4GB
mkpart win ntfs 11.4GB 209.8GB
mkpart userdata ext4 209.8GB 254GB

I have a tablet with 256GB. I haven't started the installation yet. If I change these commands like this, will it work? I want the Windows size to be larger

**Comment by n00b69** [comment]
> mkpart esp fat32 10.9GB 11.4GB mkpart win ntfs 11.4GB 209.8GB mkpart userdata ext4 209.8GB 254GB

Please use the new method, "adb shell partition 198.4" instead
