### ISSUE TITLE
Emmm...Can I use the upgrade with the MIUI system?

### ISSUE THREAD

**Issue by kujourin** [erdilS/Port-Windows-11-Xiaomi-Pad-5#71]
### Question

Can I upgrade my system in MIUI?

### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by RikuKH3** [comment]
My MIUI updating from 14.0.3 to 14.0.4 went horribly wrong. I stuck in bootloop and lost ability to boot into Android at all. "Wipe Data" from recovery menu didn't help. Had to reinstall 14.0.3 using "flash_all_except_storage.bat". Luckily it didn't removed Windows partition and dualboot works same as before.

**Comment by halal-beef** [comment]
can you close the issue now pls
