### ISSUE TITLE
[QUESTION] - Xiaomi Pad 6 Pro

### ISSUE THREAD

**Issue by felixweiid** [erdilS/Port-Windows-11-Xiaomi-Pad-5#74]
### Question

Hi, 
Does it work for Xiaomi Pad 6 Pro?

### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by halal-beef** [comment]
this repo screams mi pad 5, why are u asking such a stupid question

**Comment by halal-beef** [comment]
No
