### ISSUE TITLE
[Suggestion] - Edit the installation to this.

### ISSUE THREAD

**Issue by itayalush** [erdilS/Port-Windows-11-Xiaomi-Pad-5#76]
### Question

I found another way of connecting the Pad 5 as a storage device, Just flash the boot-nabu.img, Boot to it, choose UEFI boot options or something and then choose the option to boot to USB.
Now connect the Pad 5 to the computer, and you get the WINNABU and ESPNABU volumes on the PC!

* Don't mind that it's a "Question", There's no Suggestion option while creating issues, so I just set it to Question.

### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by halal-beef** [comment]
This method is more unsafe, it exposes every ufs lun making room for more error

**Comment by itayalush** [comment]
Thank you
