### ISSUE TITLE
[QUESTION] - <error  AddOfflineDriver>

### ISSUE THREAD

**Issue by Chris-qink5** [erdilS/Port-Windows-11-Xiaomi-Pad-5#83]
### Question

i run the command 'DriverUpdater.exe -d F:\temp\MiPad5-Drivers\definitions\Desktop\ARM64\Internal\nabu.txt -r F:\temp\MiPad5-Drivers -p X:' ,then occur  this error ' AddOfflineDriver: ntStatus=0x80070002, driverInf=F:\temp\MiPad5-Drivers\\components\QC8150\Graphics\GRAPHICS.SOC_QC8150.NABU_DESKTOP\MiPad5_dx.inf'.because  of that ,I can't  open win11 system ,can anyone help me ?

### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by n00b69** [comment]
If you still have this error with the new guide, please open a new issue. Closing this because it is using an older version of the guide.
