### ISSUE TITLE
[BUG] - WIFI not quite working on w11 instalation setup

### ISSUE THREAD

**Issue by Livb-VRC** [erdilS/Port-Windows-11-Xiaomi-Pad-5#85]
### Description

I just finished following the guide and installing w11. Seems to work but when I'm at the windows 11 setup and it asks me to connect to a network, I select one and hit next it says "Oops, you've lost internet connection"

I've tried restarting tablet and connecting to other networks same issue

Tablet is from before 2023

### Reproduction steps

```bash
- Install w11
- Go through setup
- Connect to network and hit next
```

### Agreement

- [X] I am using the latest Drivers.
- [X] I am running Windows 11 On The Tablet.
- [X] There is no issue already describing my problem.

**Comment by Livb-VRC** [comment]
For anyone having the same issue: I was able to get around this by:

In this screen, open the icon accessibility and enable on screen keyboard After that Shift + fn + f10 The cmd Will appear Type : OOBE\BYPASSNRO"

**Comment by Shad0w0ne** [comment]
hello, great that help a lot
