### ISSUE TITLE
[QUESTION] - Can WSL2 be used?

### ISSUE THREAD

**Issue by Livb-VRC** [erdilS/Port-Windows-11-Xiaomi-Pad-5#90]
### Question

I tried to run WSL2 however I get the following error:

```
WslRegisterDistribution failed with error: 0x80370102
Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.
For information please visit https://aka.ms/enablevirtualization
```

At this step I'm stuck cause I don't know how to get into the BIOS or if there's a BIOS at all

### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by halal-beef** [comment]
no u can't, virtualisation can't be used
