### ISSUE TITLE
[QUESTION] - Windows 11 Single System, without dual boot

### ISSUE THREAD

**Issue by MinGW32-2006** [erdilS/Port-Windows-11-Xiaomi-Pad-5#96]
### Question

Is there a method to remove MIUI and have only Windows 11 on ROM? I don't need android any more.

### Agreement

- [x] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by Youriywot** [comment]
I use only windows 11, if you delete androyd or delete userdata, you will get a brick, I have userdata only for show, 800mb, it also happens when windows reboots uefi-boot flies, that is, you get into fastboot ...

**Comment by musapnr** [comment]
> I use only windows 11, if you delete androyd or delete userdata, you will get a brick, I have userdata only for show, 800mb, it also happens when windows reboots uefi-boot flies, that is, you get into fastboot ...

Is it possible to shrink the Android partition like this before installation?

mkpart esp fat32 10.9GB 11.4GB
mkpart win ntfs 11.4GB 209.8GB
mkpart userdata ext4 209.8GB 254GB

**Comment by Jbrimbelibap** [comment]
> > I use only windows 11, if you delete androyd or delete userdata, you will get a brick, I have userdata only for show, 800mb, it also happens when windows reboots uefi-boot flies, that is, you get into fastboot ...
> 
> Is it possible to shrink the Android partition like this before installation?
> 
> mkpart esp fat32 10.9GB 11.4GB mkpart win ntfs 11.4GB 209.8GB mkpart userdata ext4 209.8GB 254GB

It is possible, I have done it myself. I left something like 8GB of storage for android.

You can also have multiple NTFS partitions to simulate multiple disks in windows, formatting userdata as NTFS is also possible (although I would advise against it for Nabu : no EDL restore without paying)

**Comment by EralpCelebi** [comment]
Would this be possible through a custom recovery (TWRP) and parted? Do we avoid deleting partitions because Windows sends broken/wrong UFS commands or the UFS commands being misinterpreted by the tablet? @Jbrimbelibap

**Comment by n00b69** [comment]
Deleting Android is not recommended because charging in Windows is problematic. You can run adb shell partition 110 (or 238) to nearly maximize the Windows partition, whilst being able to boot to Android just to charge.

**Comment by EralpCelebi** [comment]
I understand, thank you for your answer. I don't know much about Windows or UEFI development but what is the issue with charging? I wouldn't mind looking into it.

**Comment by Jbrimbelibap** [comment]
> Would this be possible through a custom recovery (TWRP) and parted? Do we avoid deleting partitions because Windows sends broken/wrong UFS commands or the UFS commands being misinterpreted by the tablet? @Jbrimbelibap

You can absolutely use parted in TWRP, just paste in into /sbin and chmod 755 using the included file explorer

Also charging in windows is just very slow, I feel like it works better using an official 33W Xiaomi charger though
I haven't booted android in months, you can manage just fine using only windows

**Comment by EralpCelebi** [comment]
Thank you for your response @Jbrimbelibap, I don't personally mind slow charging but I have been unable to charge my tablet with or without the 33W Xiaomi charger. I have seen another issue mentioning them flashing a modified boot image, is that the procedure I am supposed to follow? or is there something else I should be doing.

**Comment by n00b69** [comment]
> Thank you for your response @Jbrimbelibap, I don't personally mind slow charging but I have been unable to charge my tablet with or without the 33W Xiaomi charger. I have seen another issue mentioning them flashing a modified boot image, is that the procedure I am supposed to follow? or is there something else I should be doing.

Are you using the latest drivers and UEFI?

**Comment by EralpCelebi** [comment]
Yup. I will try again today with a new install of Windows.

**Comment by EralpCelebi** [comment]
Nope, still no charging sadly :/

**Comment by EralpCelebi** [comment]
I don't know how to proceed with this but I had seen a few things about booting into fastboot in order to benefit from quick charging when I was working on mainlining. Could this work? I can't really confirm what's going on because the battery decides it's thirty percent more charged this boot randomly :)

**Comment by n00b69** [comment]
> Nope, still no charging sadly :/

Do you have a USB-C to USB-C cable? Try charging with that.

> booting into fastboot in order to benefit from quick charging

Works, but it isn't quick charging.

**Comment by n00b69** [comment]
Considering this is unrelated to the initial issue, I am closing it. If you have other questions, please join the Telegram at https://t.me/nabuwoa (preferred) or open a new issue

**Comment by Jbrimbelibap** [comment]
Charging didn't work for me this morning using my friends charger and cable, but it did work using the official Xiaomi charger and cable. Make sure you're also using the official cable
